[snowflake]
account   = "ATGFFJL-QEB15691"
user      = "urbanpulse_svc"
password  = "UrbanPulse2026!"
role      = "urbanpulse_role"
warehouse = "URBANPULSE_TRANSFORM_WH"
database  = "URBANPULSE"
schema    = "MARTS"
